---
- import_tasks: install.yml
  tags: nginx_install
  when: nginx_install

- block:
  - name: mkdir cert folder
    file: path='{{ cert_base_path }}' state=directory

  - name: copy cert
    copy: src='{{ cert }}' dest='{{ cert_path }}'
    notify: reload nginx

  - name: copy cert key
    copy: src='{{ cert_key }}' dest='{{ cert_key_path }}' mode=0600
    notify: reload nginx

  - name: setup http->https redirect
    template: src=redirect.j2 dest='/etc/nginx/sites-enabled/{{ domain }}_redirect'
    when: redirect_http
    notify: reload nginx
  when: ssl

- name: basic nginx configuration
  template: src='nginx.conf.j2' dest=/etc/nginx/nginx.conf
  notify: restart nginx
- name: add nginx user
  user: name='{{ nginx_user }}' shell=/bin/false
- name: mkdir sites-enabled directory
  file: name=/etc/nginx/sites-enabled state=directory
